"""Seed selection: the step between candidate generation and the genome rescan (HANDOFF 7.7).

The bug this pins. `seed_seqs` used to take the width of the single top-scoring candidate as an anchor
and delete every candidate outside +/- 3 bp of it. The score doing that ordering -- `2*matches -
half_width` -- was measured at AUC 0.250 against 203 known operators (0.557 length-normalised, i.e. no
signal), so a wrong winner did not merely rank the right answer badly, it removed it from the seed set.
Worked case TtgR: the true 28 bp operator was generated byte-identical at rank 3 of 8, evicted by a
23 bp anchor, the seed PWM was then built from three GC-rich decoys, the genome rescan returned 110
hits none on the site, and all five exported AF3 jobs pointed at the wrong DNA.

Why re-ranking the anchor is NOT the fix. Measured on the RegulonDB panel by COORDINATE OVERLAP (the
project's standing rule -- scoring operators by sequence identity is the Stanton-2014 trap), over the 72
sites the finders cover: plain `final` retains 37, `final x AT` 33, `final x composition_prior` 39 --
and on the metal families specifically 23, 15 and 20. Every single-anchor rule only moves who loses, and
the two composition-aware ones are *worse than the status quo on metals*, so neither ships.

What ships keeps EVERY width as its own seed set and rescans the genome with each, letting the genome
decide: **72/72 retained, metals 33/33**. These tests therefore assert the invariant "no candidate is
dropped", not "the right candidate wins" -- winning is the rescan's job.

Offline and deterministic.
"""
import pytest

from predictor.signals import motif_finder as MF


class Cand:
    """Minimal stand-in for an OperatorCandidate: seed selection only reads these four attributes."""

    def __init__(self, seq, score=1.0, kind="IR", conservation=0.0):
        self.seq = seq
        self.score = score
        self.final = score * (1.0 + conservation)
        self.kind = kind
        self.conservation = conservation


AT_RICH_28 = "TACTTACATTCATGGTTGTTTGTAAATA"          # TtgR's true operator, 28 bp, AT 0.75
GC_DECOY_23 = "CCCGCACGCGCTGCGCGTTCGGG"             # the decoy that beat it, 23 bp, AT 0.17
MID_25 = "TCAAGAGTAATGGAAGAGATCTTGA"                # 25 bp, AT 0.64


class TestNoEviction:
    """The invariant. Every generated candidate must reach some seed set."""

    def test_every_candidate_survives(self):
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0),
                 Cand("AAAATTTTAA", 5.0), Cand("GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC", 4.0)]
        clusters = MF.seed_clusters(cands)
        pooled = {s for seqs, _w in clusters for s in seqs}
        assert pooled == {c.seq for c in cands}, "seed_clusters must not drop any candidate"

    def test_ttgr_true_operator_is_not_evicted(self):
        """The exact TtgR configuration: a GC-rich 23 bp decoy outscores the true 28 bp operator."""
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0)]
        clusters = MF.seed_clusters(cands)
        assert any(AT_RICH_28 in seqs for seqs, _w in clusters)

    def test_clusters_are_width_coherent(self):
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0),
                 Cand("AAAATTTTAA", 5.0)]
        for seqs, _w in MF.seed_clusters(cands):
            widths = [len(s) for s in seqs]
            assert max(widths) - min(widths) <= 2 * 3, "a cluster must stay within +/- tol of its anchor"

    def test_clusters_are_disjoint(self):
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0),
                 Cand("AAAATTTTAA", 5.0)]
        clusters = MF.seed_clusters(cands)
        seen = [s for seqs, _w in clusters for s in seqs]
        assert len(seen) == len(set(seen))

    def test_a_cap_reintroduces_eviction_and_is_therefore_not_the_default(self):
        """Pins WHY `max_clusters` defaults to None: capping is exactly the old bug, one rank further
        down. Measured on CueR, whose true 19 bp operator lands in the 4th cluster."""
        import inspect
        assert inspect.signature(MF.seed_clusters).parameters["max_clusters"].default is None
        cands = [Cand("G" * 33, 9.0), Cand("A" * 27, 8.0), Cand("AT" * 7 + "A", 7.0),
                 Cand(("AC" * 10)[:19], 6.0)]
        capped = MF.seed_clusters(cands, max_clusters=3)
        uncapped = MF.seed_clusters(cands)
        assert sum(len(s) for s, _ in capped) < sum(len(s) for s, _ in uncapped)

    def test_seed_seqs_is_the_first_cluster(self):
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0)]
        clusters = MF.seed_clusters(cands)
        assert MF.seed_seqs(cands) == clusters[0][0]

    def test_empty_input(self):
        assert MF.seed_clusters([]) == []
        assert MF.seed_seqs([]) == []

    def test_dyads_are_preferred_over_pwm_seeded_hits(self):
        """Unchanged behaviour: PWM/family-seeded single hits score on a different scale and must not
        set the seed when real dyads exist."""
        cands = [Cand(AT_RICH_28, 6.0, kind="IR"), Cand(GC_DECOY_23, 99.0, kind="pwm")]
        pooled = {s for seqs, _w in MF.seed_clusters(cands) for s in seqs}
        assert pooled == {AT_RICH_28}

    @pytest.mark.parametrize("n_extra", [0, 3, 10])
    def test_invariant_holds_at_any_candidate_count(self, n_extra):
        """`top_k` is 24 in production, not 8, so the seed step must stay lossless as the pool grows."""
        cands = [Cand(GC_DECOY_23, 7.0), Cand(MID_25, 6.0), Cand(AT_RICH_28, 6.0),
                 Cand("AAAATTTTAA", 5.0)]
        cands += [Cand("ACGT" * (3 + i), 4.0 - 0.1 * i) for i in range(n_extra)]
        pooled = {s for seqs, _w in MF.seed_clusters(cands) for s in seqs}
        assert pooled == {c.seq for c in cands}

    def test_seed_selection_is_family_agnostic(self):
        """No family parameter, by design: the composition-aware ordering was measured worse than plain
        `final` on the metal families (20/33 vs 23/33) and is not shipped. Pinned so it is not re-added
        without a measurement."""
        import inspect
        params = set(inspect.signature(MF.seed_clusters).parameters)
        assert "family" not in params and "exclude_tf" not in params
        assert not hasattr(MF, "composition_prior")
