"""build_reports.py -- BENCHMARK_REPORT.md and SURVEY_REPORT.md, written from numbers.json.

Two documents, never one: the benchmark genomes have a knowledge base and may carry accuracy
claims; the survey genomes have no operator truth set and may not. No number is typed by hand here;
every figure referenced is built by build_{benchmark,survey}_figures.py from the same JSON.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def pct(text: str) -> str:
    """'5/24' -> '5/24 (21%)'."""
    a, b = (int(x) for x in text.split()[0].split("/"))
    return f"{a}/{b} ({100 * a / b:.0f}%)" if b else text


def benchmark_report(N: dict) -> str:
    p, b = N["provenance"], N["benchmark"]
    eco, salm = b["ecoli"], b["salmonella"]
    rec, sc, ssc = eco["recall"], eco["scores"], salm["scores"]
    cen, src = eco["census"], eco["sources"]
    m, sm = sc["ion"], ssc["ion"]
    acct = b["metal_sensor_accounting"]
    tot = acct["ecoli_census_totals"]
    op_e, op_s = sc["operator"]["all"], ssc["operator"]["all"]
    no_effector = len(eco["per_tf"]) - sc["class"]["n"]
    miss = rec["miss_reasons"]
    L = [
        "# Benchmark report — E. coli K-12 and Salmonella Typhimurium SL1344",
        "",
        f"Run `{p['runs']['ecoli']['tag']}` and `{p['runs']['salmonella']['tag']}`, predictor commit "
        f"`{p['predictor_commit']}`, structure prediction off. Generated by `build_reports.py` from "
        "`numbers.json`; every number traces to the canonical run.",
        "",
        "These are the two genomes with a knowledge base, so this is the only document that makes "
        "accuracy claims. The four survey genomes are reported separately.",
        "",
        "## What is being measured against what",
        "",
        f"- **E. coli truth**: RegulonDB release {src['release']} and UniProt release "
        f"{src['uniprot']['release']} ({src['uniprot']['release_date']}), assembled into a census of "
        f"**{cen['tf']} transcription factors** ({cen['tf_in_regulondb']} RegulonDB TFs plus "
        f"{cen['tf'] - cen['tf_in_regulondb']} further K-12 proteins carrying a studied family's "
        f"signature domain), of which **{cen['in_study_families']}** are in the twelve studied "
        f"families and **{cen['metal_sensors']}** are metal sensors. A TF is in a studied family when it "
        "carries the family's signature Pfam or the paper's own family sequence set lists it; the second "
        "rule places ModE in LysR, since UniProt cross-references only its molybdate-binding domain. "
        "The census holds "
        f"{cen['interactions']} regulatory interactions, **{cen['precise_operators']}** of them "
        "precise operators. Full text: `analysis/benchmarking/ecoli_kb/E_coli_knowledge.md`.",
        f"- **Salmonella truth**: {salm['source']}.",
        "",
        "**Definitions used throughout.**",
        "",
        f"- *Primary operator* — {N['definitions']['primary_operator']}",
        f"- *Precise operator* (truth) — {N['definitions']['precise_operator']}",
        f"- *Operator on site* — {N['definitions']['operator_on_site']}",
        f"- *Proximal vs distal* — {N['definitions']['proximal_vs_distal']}",
        "- *Scoring unit* — every axis is scored over all discovered TFs that have truth for that axis, "
        "so denominators differ by axis and are always given. Chance expectations for operators come "
        "from `analysis/benchmarking/genome_scoring.py`.",
        "",
        "## 1. Discovery: does the search reach the transcription factors that exist?",
        "",
        f"The E. coli census holds **{tot['tfs']} TFs**: **{tot['in_study_families']}** in the twelve "
        f"studied families and {tot['other_families']} in other families, which discovery does not "
        f"search. Of the **{rec['n_in_study_families']}** census TFs in the twelve studied families, the run "
        f"discovered **{pct(rec['recall_in_study_families'])}**, from a candidate list of "
        f"{rec['n_candidates']}. No discovered protein lies outside the census "
        f"({len(rec['discovered_not_in_census'])} such candidates).",
        "",
        "Every miss is attributed to the step that lost it, read from the search's own tables:",
        "",
        "| reason | TFs | meaning |",
        "|---|---|---|",
        f"| profile scope | {miss['profile_scope']} | no clade profile of the TF's own family reports it at all |",
        f"| threshold | {miss['threshold']} | its family's profile reports it, but above the 1e-5 cut |",
        f"| curation | {miss['curation']} | it passed the cut and a downstream step dropped it |",
        "",
        f"**Metal sensors: {len(rec['metal_sensors_found'])}/{len(rec['metal_sensors_in_study_families'])} "
        f"recovered** ({', '.join(rec['metal_sensors_found'])}).",
    ]
    if rec["metal_sensors_missed"]:
        for tf, why in rec["metal_sensors_missed"].items():
            L.append(f"The one miss is **{tf}** ({why.replace('_', ' ')}).")
    e = rec["enrichment_vs_study_families"]
    e2 = rec["enrichment_vs_all_census_tfs"]
    L += [
        "",
        f"Metal sensors are **enriched among the candidates**: {e['metal_fraction_among_found']:.0%} of "
        f"discovered TFs versus {e['metal_fraction_in_population']:.0%} of all in-family TFs "
        f"(odds ratio {e['odds_ratio']}, P = {e['p_one_sided']:.3g}, one-sided Fisher exact); against "
        f"the whole census, {e2['metal_fraction_among_found']:.0%} versus "
        f"{e2['metal_fraction_in_population']:.0%} (odds ratio {e2['odds_ratio']}, "
        f"P = {e2['p_one_sided']:.3g}).",
        "",
        "Metal sensors the twelve families cannot reach by construction, listed so the ceiling is "
        "explicit: " + ", ".join(f"{k} ({v})" for k, v in rec["metal_sensors_outside_study_families"].items()) + ".",
        "",
        "## 2. Metal sensors: which were found, missed or misassigned",
        "",
        "| genome | sensor | known ion(s) | studied family | found | called | outcome |",
        "|---|---|---|---|---|---|---|",
    ]
    for s_ in acct["sensors"]:
        if s_["discovered"] != "yes":
            outcome = ("missed: no clade profile reaches it" if s_["miss_reason"] == "profile_scope"
                       else "not searched: family outside the twelve")
        else:
            outcome = {"hit": "exact ion", "shortlist": "ion in the shortlist, not first",
                       "class only": "metal class, ion unresolved"}.get(s_["ion"], "wrong ion")
        L.append(f"| {s_['genome']} | {s_['tf']} | {s_['known_ions'].replace(';', ', ')} | {s_['family']} | "
                 f"{s_['discovered']} | {s_['called'] or '—'} | {outcome} |")
    for fm in acct["false_metal"]:
        L.append(f"| {fm['genome']} | {fm['tf']} (non-metal) | — | — | yes | {fm['called']} | "
                 f"false metal call (agreement {fm['agreement']}) |")
    L += [
        "",
        f"> **Independence.** {b['independence_caveat']}",
        "",
        "## 3. Accuracy, axis by axis",
        "",
        "| axis | E. coli K-12 | Salmonella SL1344 |",
        "|---|---|---|",
        f"| in-family TFs discovered | {sc['discovery']['in_family_discovered']}/{sc['discovery']['in_family_total']} "
        f"| {ssc['discovery']['in_family_discovered']}/{ssc['discovery']['in_family_total']} (UniProt census, lower bound) |",
        f"| family | {sc['family']['correct']}/{sc['family']['n']} | {ssc['family']['correct']}/{ssc['family']['n']} |",
        f"| inducer class | {sc['class']['correct']}/{sc['class']['n']} | {ssc['class']['correct']}/{ssc['class']['n']} (Osman sensors) |",
        f"| metal ion, exact | {m['hit']}/{m['n']} | {sm['hit']}/{sm['n']} |",
        f"| primary operator on a confirmed site | {op_e['1']['observed']}/{op_e['n']} "
        f"(chance {op_e['1']['expected_by_chance']}) | {op_s['1']['observed']}/{op_s['n']} "
        f"(chance {op_s['1']['expected_by_chance']}) |",
        "",
        f"The class denominator is smaller than the family one because {no_effector} discovered E. coli "
        "TFs have no effector recorded in RegulonDB or the curation table, so their class cannot be "
        "scored. In SL1344, class, ion and operator truth exist only for the Osman sensors; the "
        f"operator axis excludes {', '.join(ssc['operator'].get('excluded', [])) or 'none'} (no "
        "experimentally supported target in this organism).",
        "",
        "## 4. Operators",
        "",
        f"- Primary operator on a confirmed site: **{op_e['1']['observed']}/{op_e['n']}** E. coli TFs "
        f"(chance {op_e['1']['expected_by_chance']}, P = {op_e['1']['p_vs_chance']:.2g}); "
        f"{op_s['1']['observed']}/{op_s['n']} Salmonella sensors.",
        "- By locality: " + ", ".join(f"{v} {k}" for k, v in op_e["primary_hits_by_locality"].items() if v)
        + ". A proximal hit is one the locality prior already favours; a distal hit is one the motif placed.",
        f"- Looser cut-offs were measured and add little: E. coli top-5 {op_e['5']['observed']}/{op_e['n']}, "
        f"top-10 {op_e['10']['observed']}/{op_e['n']}, every site {op_e['all']['observed']}/{op_e['n']} "
        f"(chance {op_e['all']['expected_by_chance']}). The primary operator is therefore the only cut "
        "reported in the figures.",
        f"- Against high-throughput binding sites instead of confirmed ones: "
        f"{sc['operator_ht']['all']['1']['observed']}/{sc['operator_ht']['all']['n']} at the primary operator.",
        f"- {N['definitions']['regulon_cap']}",
        "",
        "## 5. What this supports, and what it does not",
        "",
        "- **Supported.** The family and inducer-class calls are reliable on both genomes; the exact "
        "metal ion is right for all but one sensor in each genome; discovery reaches the metal-sensing "
        "repertoire of the studied families and is enriched for it.",
        "- **Not supported.** Operator placement: most predicted primary operators do not fall on a "
        "confirmed site, and most of those that do are the regulator's own promoter, which the locality "
        "prior already favours. Regulon precision follows the operator, and is low.",
        "- **Not tested here.** The independence of the inducer call, for the reason in section 2.",
        "",
        "## Figures",
        "",
        "- `figures/figB_benchmark.*` — the family census, accuracy per axis, the class confusion "
        "matrix, and the metal-sensor accounting.",
        "- `figures/figB_S1_per_regulator.*` — every discovered TF of both genomes, by axis.",
        "",
        "## Source data",
        "",
        "`analysis/benchmarking/ecoli_kb/`: `E_coli_knowledge.md`, `ecoli_tf.tsv`, `ecoli_sites.tsv`, "
        "`ecoli_regulon.tsv`, `discovery_recall.tsv`, `discovered_scores.tsv`. "
        "`analysis/benchmarking/salmonella/`: `osman2019_targets.tsv`, `salmonella_family_census.tsv`, "
        "`discovered_scores.tsv`. Scoring: `analysis/benchmarking/genome_scoring.py`; what the "
        "Salmonella benchmark still lacks: the change log of `ecoli_kb/PANEL_CRITERIA.md`. Run "
        "pointers: `analysis/canonical_runs.toml`.",
        "",
    ]
    return "\n".join(L)


def survey_report(N: dict) -> str:
    p, s, per = N["provenance"], N["survey"]["all"], N["survey"]["per_genome"]
    f = s["metal_funnel"]
    L = [
        "# Survey report — four genomes",
        "",
        f"Run `{p['runs']['survey']['tag']}`, predictor commit `{p['predictor_commit']}`, structure "
        "prediction off. Generated by `build_reports.py` from `numbers.json`.",
        "",
        "> **No accuracy claim appears in this document.** These genomes have no curated operator or "
        "inducer truth set, so every number below describes what the pipeline returned, not how often "
        "it was right. Accuracy is measured only on the two benchmark genomes.",
        "",
        f"## The candidate set: {s['n']} regulators across four genomes",
        "",
        "| genome | candidates | metal calls | corroborated | ion resolved | own promoter in the top 5 |",
        "|---|---|---|---|---|---|",
    ]
    for g, c in per.items():
        mf = c["metal_funnel"]
        L.append(f"| {g} | {c['n']} | {mf['metal_calls']} ({100 * mf['metal_calls'] / c['n']:.0f}%) | "
                 f"{mf['corroborated']} | {mf['ion_resolved']} | {c['autoregulation']['n']} "
                 f"({c['autoregulation']['pct']:.0f}%) |")
    L += [
        f"| **all four** | **{s['n']}** | **{f['metal_calls']} ({100 * f['metal_calls'] / s['n']:.0f}%)** | "
        f"**{f['corroborated']}** | **{f['ion_resolved']}** | **{s['autoregulation']['n']} "
        f"({s['autoregulation']['pct']:.0f}%)** |",
        "",
        "## The metal calls",
        "",
        f"Of {s['n']} candidates, **{f['metal_calls']}** are called metal sensors. "
        f"**{f['corroborated']}** of those are corroborated — {N['definitions']['corroborated_metal_call']} "
        f"— and **{f['ion_resolved']}** name a specific ion or oxyanion:",
        "",
        "| ion | calls |",
        "|---|---|",
    ]
    L += [f"| {k} | {v} |" for k, v in f["ions"].items()]
    L += [
        "",
        f"**Operator support.** One of the top-{s['autoregulation']['top_k']} operators lies in the "
        f"regulator's own flanking intergenic region for {s['autoregulation']['n']}/{s['n']} candidates "
        f"({s['autoregulation']['pct']:.0f}%). Among the metal calls, "
        f"{s['operator_supports_metal_call']['n']}/{s['operator_supports_metal_call']['of_metal_calls']} "
        f"({s['operator_supports_metal_call']['pct']:.0f}%) carry such an operator, so for those the "
        "metal call and the operator point at the same locus. The locality prior favours this region, "
        "so it is support, not independent proof.",
        "",
        "## Motif quality, stated plainly",
        "",
        f"Median PWM information content is {s['pwm']['median_mean_ic_bits']} bits per column, built from a "
        f"median of {s['pwm']['median_homologs']} homologues (range {s['pwm']['homolog_range'][0]}–"
        f"{s['pwm']['homolog_range'][1]}). {N['definitions']['regulon_cap']} On the benchmark genomes a "
        "predicted primary operator lands on a confirmed site about a fifth of the time; there is no "
        "reason to expect a higher rate here, and the operator and regulon columns of this survey should "
        "be read as hypotheses to test, not findings.",
        "",
        "## Figures",
        "",
        "- `figures/figS_survey.*` — family composition, inducer class, the metal funnel, "
        "autoregulation and operator support, per genome.",
        "- `figures/figS_S1_benchmark_genomes.*` — the two benchmark genomes on the same axes, for "
        "comparability.",
        "",
        "## Source data",
        "",
        "`<run root>/results/operator_predictions.csv` and the per-regulator bundles under "
        "`<run root>/jobs/`, with the run named in `analysis/canonical_runs.toml`.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    N = json.loads((HERE / "numbers.json").read_text(encoding="utf-8"))
    for name, text in (("BENCHMARK_REPORT.md", benchmark_report(N)),
                       ("SURVEY_REPORT.md", survey_report(N))):
        (HERE / name).write_text(text, encoding="utf-8")
        print(f"  wrote {name} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
