#!/usr/bin/env python
"""run_discovery.py -- genomes in, run manifest out. The first stage of a production run.

Until now every batch started from `analysis/run_manifest.csv`, a frozen list of 150 candidates
inherited from the survey. That made the discovery half of the pipeline unrunnable: we could
reproduce the survey's answer but not its question. This script is the missing entry point --
BITACORA over whole genomes, exactly the route Rondon et al. used -- and it writes a manifest in the
same schema the batch already consumes, plus provenance columns saying how each row was found.

    python analysis/run_discovery.py --tag prod20260820            # the four survey genomes
    python analysis/run_discovery.py --tag t --genomes GCF_000195955.2
    python analysis/run_discovery.py --tag t --census-fallback     # allow the Pfam census if no engine

Three things it refuses to do, each for a reason that has already cost this project something:

**It will not silently substitute the census for BITACORA.** They reach nearly the same candidate set
(149/150 by accession, `benchmarking/discovery/DISCOVERY_DECISION_20260819.md`) but they are different
methods, and a manifest that does not say which one produced it cannot be compared to the survey.
Without the engine this stops, unless `--census-fallback` says otherwise -- and then it records
`discovery_engine=pfam_census` on every row it writes.

**It will not write trimmed sequences.** BITACORA's headline output is cut to the matched domain,
which is why the survey's manifest lists IdeR at 154 aa against its real 230. Trimmed sequences
cannot be joined to anything and cannot be folded. The FASTA written per candidate is full-length;
the trim rides along as `trim_start`/`trim_end`.

**It will not overwrite `run_manifest.csv`.** That file is the survey's 150 and is reference data for
every comparison we make. A discovery run writes `run_manifest_<tag>.csv` beside it.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

from project_config import PREDICTOR_ROOT

PROJ = Path(__file__).resolve().parent.parent
ANALYSIS = PROJ / "analysis"
REPO = PREDICTOR_ROOT

sys.path.insert(0, str(REPO))
from predictor.annotate.genome_db import MIRROR_DIR as MIRROR  # noqa: E402

#: The four genomes of the survey. Short names are the existing manifest's `run_name` prefixes so a
#: genome-first run and the frozen 150 stay directly comparable.
#:
#: DERIVED FROM `analysis/run_manifest.csv`, not from memory. A hand-written version of this table
#: had three of the four accessions attached to the wrong organism -- GCF_002224265.1 labelled
#: M. avium when it is V. vulnificus, and GCF_004345205.2/GCF_008369605.1 swapped -- which would have
#: mislabelled the organism on every row of the production manifest while looking entirely normal.
#: `truth_key` is the spelling used by `collaborator_mining/master_candidates.tsv`, which differs
#: again (`Mavi_homi`), and is what the discovery scorer joins on.
GENOMES = {
    "GCF_000195955.2": ("MtubH37Rv", "Mycobacterium tuberculosis H37Rv"),
    "GCF_002224265.1": ("VvulNBRC", "Vibrio vulnificus NBRC 15645"),
    "GCF_004345205.2": ("MaviHomi", "Mycobacterium avium subsp. hominissuis mc2 2500"),
    "GCF_008369605.1": ("VchoRFB16", "Vibrio cholerae RFB16"),
}

#: Benchmark organisms. DELIBERATELY NOT IN `GENOMES`, because `--genomes` defaults to that dict and
#: adding one here would silently fold a benchmark organism into the survey's candidate set -- the
#: paper would then report predictions for proteins that were never part of the survey. They are
#: named here only so a benchmark run gets a readable short name instead of an autogenerated one, and
#: they must be requested explicitly:
#:
#:     python analysis/run_discovery.py --tag <tag> --genomes GCF_000210855.2
BENCHMARK_GENOMES = {
    # Salmonella enterica subsp. enterica serovar Typhimurium SL1344, taxon 216597.
    # Chromosome NC_016810.1 (4,878,012 bp) + plasmids NC_017718.1, NC_017719.1, NC_017720.1.
    # The tier-2 operator/regulon benchmark: Osman et al. 2019 Nat. Chem. Biol. 15:241-249
    # characterise seven metal sensors in THIS strain with 52 curated DNA targets between them.
    # See analysis/benchmarking/salmonella/.
    "GCF_000210855.2": ("SentSL1344", "Salmonella enterica serovar Typhimurium SL1344"),
}
#: accession -> the genome key used by the survey's published tables
TRUTH_KEY = {
    "GCF_000195955.2": "MtubH37Rv",
    "GCF_002224265.1": "VvulNBRC",
    "GCF_004345205.2": "Mavi_homi",
    "GCF_008369605.1": "VchoRFB16",
}

# The discovery logic lives in the package (predictor.genome_run), shared with `tfop genome` and the
# GUI, so this driver and a public user's run cannot drift apart. What stays here is what is specific
# to this project: run tags, the survey genomes' short names, and the comparison against the survey.
from predictor import genome_run as GR  # noqa: E402

MANIFEST_COLS, PROV_COLS, safe = GR.MANIFEST_COLS, GR.PROV_COLS, GR.safe


def discover(acc: str, *, census_fallback: bool, verbose: bool) -> tuple[list, str, str]:
    """(candidates, engine, protein_source) for one mirrored genome."""
    fna = MIRROR / f"{acc}.fna"
    if not fna.exists():
        raise SystemExit(f"genome not mirrored: {fna}\nfetch it first: "
                         f"`tfop genome {acc} --discover-only --out <scratch dir>` "
                         f"(or PRODUCTION_RUNBOOK.md §6b)")
    try:
        return GR.discover(fna, census_fallback=census_fallback, verbose=verbose)
    except RuntimeError as exc:
        raise SystemExit(str(exc)) from exc


def compare_to_survey(rows: list, genomes: list) -> None:
    """Print the manifest against the survey's published candidates, per genome.

    This runs at the end of every discovery run because the comparison is free and the alternative
    is finding out after a multi-hour batch. Two columns, and the SECOND is the one that decides:
    a candidate the survey lists but which carries no predicted metal site is a row our inducer
    stage abstains on anyway, so losing it costs a table entry; losing a site-bearing one costs a
    result. See `benchmarking/discovery/PROFILE_SCOPE_DECISION_20260820.md`.
    """
    truth = PROJ / "analysis" / "collaborator_mining" / "master_candidates.tsv"
    if not truth.exists():
        return
    t_all: dict[str, set] = {}
    t_site: dict[str, set] = {}
    with truth.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            t_all.setdefault(r["genome"], set()).add(r["accession"])
            if (r.get("has_metalnet_site") or "").strip().lower() == "yes":
                t_site.setdefault(r["genome"], set()).add(r["accession"])

    ours: dict[str, set] = {}
    for r in rows:
        ours.setdefault(r["organism_acc"], set()).add(r["run_name"].rsplit("__", 1)[-1])

    print(f"\n{'genome':<20}{'ours':>6}{'survey':>8}{'recall(all)':>14}{'recall(SITE+)':>16}")
    tot_o = tot_t = 0
    for acc in genomes:
        key = TRUTH_KEY.get(acc, "")
        ta, ts = t_all.get(key, set()), t_site.get(key, set())
        o = ours.get(acc, set())
        tot_o += len(o)
        tot_t += len(ta)
        if not ta:
            print(f"{acc:<20}{len(o):>6}{'-':>8}{'(no truth rows)':>14}")
            continue
        # accessions in the manifest carry our safe() spelling; the survey's do not differ, but
        # compare on the raw protein id to be sure rather than on the run_name
        ra = len(o & ta) / len(ta)
        rs = (len(o & ts) / len(ts)) if ts else 0.0
        print(f"{key:<20}{len(o):>6}{len(ta):>8}{len(o & ta):>7}/{len(ta)} {ra:>4.0%}"
              f"{len(o & ts):>9}/{len(ts)} {rs:>4.0%}")
    print(f"{'TOTAL':<20}{tot_o:>6}{tot_t:>8}")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tag", required=True, help="names the manifest and the FASTA directory")
    ap.add_argument("--genomes", nargs="*", default=list(GENOMES),
                    help="organism accessions (default: the four survey genomes)")
    ap.add_argument("--census-fallback", action="store_true",
                    help="use the Pfam census when the BITACORA engine is unavailable")
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args(argv)

    fasta_root = ANALYSIS / f"tf_fastas_{safe(a.tag)}"
    manifest = ANALYSIS / f"run_manifest_{safe(a.tag)}.csv"
    if manifest.exists():
        print(f"! {manifest.name} already exists -- pick another tag rather than merging two "
              f"discovery runs into one manifest")
        return 1

    rows, engines = [], set()
    for acc in a.genomes:
        short, organism = {**GENOMES, **BENCHMARK_GENOMES}.get(acc, (safe(acc), acc))
        print(f"[{acc}] {organism}")
        cands, engine, psource = discover(acc, census_fallback=a.census_fallback, verbose=a.verbose)
        engines.add(engine)
        gff = MIRROR / f"{acc}.gff"
        new = GR.manifest_rows(cands, short=short, organism=organism, accession=acc, engine=engine,
                               protein_source=psource, coords=GR.gff_index(gff if gff.exists() else None),
                               fasta_dir=fasta_root / short, rel_to=PROJ)
        rows.extend(new)
        print(f"  {len(cands)} candidate(s), {len(new)} with a family -> {engine} ({psource})")

    if not rows:
        print("no candidates found -- refusing to write an empty manifest")
        return 1

    GR.write_manifest(rows, manifest)

    by_fam: dict[str, int] = {}
    for r in rows:
        by_fam[r["family"]] = by_fam.get(r["family"], 0) + 1
    print(f"\n{len(rows)} candidate(s) across {len(a.genomes)} genome(s) -> {manifest}")
    print(f"engine(s): {', '.join(sorted(engines))}")
    for f, n in sorted(by_fam.items(), key=lambda kv: -kv[1]):
        print(f"   {f:<20}{n}")
    compare_to_survey(rows, a.genomes)
    print(f"\nnext: python analysis/run_pipeline.py --manifest {manifest.name} --all --jobs 4")
    return 0


if __name__ == "__main__":
    sys.exit(main())
